#!usr/bin/env bash
# configures an ubuntu server with the below requirements.
# loc	l host resolves to 127.0.0.2
# facebook resolves to 8.8.8.8.
# The checker is running on Docker

cp /etc/hosts ~/hosts.new
echo "127.0.0.2  localhost" > ~/hosts.new
echo "8.8.8.8  facebook.con" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts