#!/usr/bin/env bash
# configures an ubuntu server with the below requirements.
# local host resolves to 127.0.0.2
# facebook resolves to 8.8.8.8.
# The checker is running on Docker

sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8  facebook.con" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts